import operator
from datetime import datetime, date
from enum import Enum
from typing import Any, List, Optional, TypedDict, Dict, Literal, Annotated
from pydantic import BaseModel, Field

class SourceType(str, Enum):
    PDF = "pdf"
    WEB = "web"
    VIDEO = "video"
    AUDIO = "audio"

class RawSource(BaseModel):
    id: str                        # UUID
    source_type: SourceType
    url: str
    content: str
    metadata: Dict[str, Any]
    trust_score: float = Field(ge=0.0, le=1.0)
    fetched_at: datetime
    embedding_index_id: Optional[str] = None  # FAISS index reference

class Claim(BaseModel):
    id: str
    content: str
    source_id: str
    confidence: float = Field(ge=0.0, le=1.0)
    supporting_quotes: List[str]
    verified: bool = False

class ContradictionSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"

class Contradiction(BaseModel):
    claim_a_id: str
    claim_b_id: str
    description: str
    severity: ContradictionSeverity

class Citation(BaseModel):
    source_id: str
    title: str
    url: str
    access_date: date
    formatted_citation: str        # APA format, generated by LLM

class ThoughtEntry(BaseModel):
    timestamp: datetime
    node: str
    thought: str
    tokens_used: int
    llm_backend: str              # "groq:llama-3.1-8b"|"ollama:qwen2.5:7b"

class ResearchState(TypedDict):
    query: str                         # Original sanitized user query
    session_id: str                    # UUID4 for tracing
    intent_classification: str         # "factual"|"analytical"|"comparative"
    
    # SOURCE TRACKING
    raw_sources: Annotated[List[RawSource], operator.add]
    source_priority: List[str]         # Ordered source IDs by trust_score
    
    # CLAIMS & VERIFICATION
    extracted_claims: Annotated[List[Claim], operator.add]
    contradictions: Annotated[List[Contradiction], operator.add]
    verified_dossier: Annotated[List[Claim], operator.add]
    
    # ADVANCED AI: GRAPHRAG & DEBATE
    graph_summary: Optional[str]               # Synthesized Knowledge Graph context
    debate_log: Annotated[List[Dict[str, str]], operator.add] # [{"role": "proposer", "content": "..."}]

    # LOOP CONTROL
    revision_count: int
    max_revisions: int                 # From config, default 5
    query_refinements: Annotated[List[str], operator.add]
    
    # RESOURCE TRACKING
    total_tokens_used: int
    token_budget: int                  # Soft limit for loop control
    budget_exceeded: bool
    
    # CONFIDENCE & EVALUATION
    confidence_score: float            # 0.0 to 1.0
    confidence_threshold: float        # From config, default 0.85
    faithfulness_score: float          # 0.0 to 1.0
    
    # LLM BACKEND INFO (for observability)
    llm_backend_used: Annotated[List[str], operator.add]        # ["groq", "ollama", "groq", ...]
    
    # STREAMING / OBSERVABILITY
    trace_id: str
    span_ids: Annotated[List[str], operator.add]
    thought_log: Annotated[List[ThoughtEntry], operator.add]
    current_node: str
    
    # OUTPUT
    final_report: Optional[str]
    citations: Annotated[List[Citation], operator.add]
    structured_output: Optional[Dict[str, Any]]
